export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_ERROR = 'FETCH_EVENT_ERROR';

export const FETCH_FAV_EVENT_REQUEST = 'FETCH_FAV_EVENT_REQUEST';
export const FETCH_FAV_EVENT_SUCCESS = 'FETCH_FAV_EVENT_SUCCESS';
export const FETCH_FAV_EVENT_ERROR = 'FETCH_FAV_EVENT_ERROR';
