export const DO_FAVORITE_REQUEST = 'DO_FAVORITE_REQUEST';
export const DO_FAVORITE_SUCCESS = 'DO_FAVORITE_SUCCESS';
export const DO_FAVORITE_ERROR = 'DO_FAVORITE_ERROR';

export const FETCH_FAVORITE_REQUEST = 'FETCH_FAVORITE_REQUEST';
export const FETCH_FAVORITE_SUCCESS = 'FETCH_FAVORITE_SUCCESS';
export const FETCH_FAVORITE_ERROR = 'FETCH_FAVORITE_ERROR';
